name: CI

on:
  push:
    branches:
      - master
      - 'feature/**'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check workflow
        run: echo "✅ Workflow attivo e funzionante!"

      - name: Checkout code
        uses: actions/checkout@v3
      - name: Check code
        run: echo "✅ Checkout effettuato con successo!"

      - name: Install dependencies
        run: npm ci
      - name: Check install
        run: echo "✅ Installazione delle dependency effettuato con successo!"

      - name: Run linter
        run: npm run lint
      - name: Check linter
        run: echo "✅ Linter eseguito con successo!"

      - name: Run Jest coverage
        run: npm run coverage
      - name: Check Jest coverage
        run: echo "✅ Jest Coverage eseguito con successo!"

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          #: ${{ secrets.CODECOV_TOKEN }} # solo se il repo è privato
          files: ./coverage/lcov.info
          flags: unittests
          name: codecov-report
      - name: Check codecov
        run: echo "✅ Coverage caricato con successo!"